# Generated by Django 4.0.5 on 2022-07-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarRooftop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Solar Rooftop Project')),
                ('file_name', models.TextField()),
                ('tags', models.TextField()),
                ('approve_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='-', max_length=255, null=True)),
            ],
        ),
    ]
