# Generated by Django 4.0.5 on 2022-07-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='file_name',
            field=models.TextField(null=True),
        ),
    ]
