# Generated by Django 4.0.5 on 2022-07-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS', '0002_alter_solarrooftop_file_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolarRooftop',
        ),
    ]
