# Generated by Django 4.0.5 on 2022-07-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='REGISTERNEWPROJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('project_owner', models.TextField()),
                ('project_objective', models.TextField()),
                ('related_system', models.TextField()),
                ('owner_area', models.CharField(max_length=255)),
                ('start_project', models.DateTimeField(auto_now_add=True)),
                ('end_project', models.DateTimeField(auto_now_add=True)),
                ('folderstructure_image', models.ImageField(upload_to='folder_structure_image')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
        ),
    ]
