# Generated by Django 4.0.5 on 2022-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0003_alter_registernewproject_start_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernewproject',
            name='folderstructure_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
