# Generated by Django 4.0.5 on 2022-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0006_alter_registernewproject_folderstructure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registernewproject',
            name='admincomment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registernewproject',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registernewproject',
            name='folderstructure_image',
            field=models.ImageField(blank=True, upload_to='design_image'),
        ),
    ]
