# Generated by Django 4.0.5 on 2022-07-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0007_registernewproject_admincomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernewproject',
            name='folderstructure_image',
            field=models.FileField(blank=True, upload_to='design_image'),
        ),
        migrations.AlterField(
            model_name='registernewproject',
            name='status',
            field=models.CharField(default='Awaitting Admin Approve', max_length=255, null=True),
        ),
    ]
