# Generated by Django 4.0.5 on 2022-07-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0008_alter_registernewproject_folderstructure_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registernewproject',
            old_name='admincomment',
            new_name='projectid',
        ),
    ]
