# Generated by Django 4.0.5 on 2022-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0009_rename_admincomment_registernewproject_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOLARROOFTOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('tags', models.TextField()),
                ('file', models.FileField(upload_to='Solar Rooftop Installation Project')),
                ('approve_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='-', max_length=255, null=True)),
            ],
        ),
    ]
