# Generated by Django 4.0.5 on 2022-07-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0010_solarrooftop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TR401',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('tags', models.TextField()),
                ('file', models.FileField(upload_to='TR401 Oil leak')),
                ('approve_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='-', max_length=255, null=True)),
            ],
        ),
    ]
