# Generated by Django 4.0.5 on 2022-07-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0011_tr401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='file',
            field=models.FileField(upload_to='Solar_Rooftop'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='file_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='file',
            field=models.FileField(upload_to='TR401_Oil'),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='file_name',
            field=models.TextField(null=True),
        ),
    ]
