# Generated by Django 4.0.5 on 2022-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0012_alter_solarrooftop_file_alter_solarrooftop_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernewproject',
            name='building',
            field=models.CharField(max_length=255),
        ),
    ]
