# Generated by Django 4.0.5 on 2022-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0013_alter_registernewproject_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='registernewproject',
            name='approver_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registernewproject',
            name='approver_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registernewproject',
            name='approver_3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
