# Generated by Django 4.0.5 on 2022-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0014_registernewproject_approver_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarrooftop',
            name='approve_date',
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
