# Generated by Django 4.0.5 on 2022-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0015_remove_solarrooftop_approve_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.TextField(null=True),
        ),
    ]
