# Generated by Django 4.0.5 on 2022-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0016_solarrooftop_endfile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.TextField(null=True),
        ),
    ]
