# Generated by Django 4.0.5 on 2022-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0017_alter_solarrooftop_inputfile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarrooftop',
            name='retention',
            field=models.TextField(null=True),
        ),
    ]
