# Generated by Django 4.0.5 on 2022-07-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0018_solarrooftop_retention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarrooftop',
            name='retention',
        ),
    ]
