# Generated by Django 4.0.5 on 2022-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0019_remove_solarrooftop_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
