# Generated by Django 4.0.5 on 2022-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0020_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarrooftop',
            name='retention',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
