# Generated by Django 4.0.5 on 2022-07-27 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0025_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 8, 33, 51, 608181), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 8, 33, 51, 608181), max_length=100),
        ),
    ]
