# Generated by Django 4.0.5 on 2022-07-27 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0026_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tr401',
            name='approve_date',
        ),
        migrations.AddField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 11, 10, 0, 32025), max_length=100),
        ),
        migrations.AddField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 10, 0, 32025), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 11, 10, 0, 32025), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 10, 0, 32025), max_length=100),
        ),
    ]
