# Generated by Django 4.0.5 on 2022-08-04 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0032_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 14, 4, 10, 55384), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='file_name',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 14, 4, 10, 55384), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='tags',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 28, 14, 4, 10, 55384), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='file_name',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 14, 4, 10, 55384), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='tags',
            field=models.CharField(max_length=38, null=True),
        ),
    ]
