# Generated by Django 4.0.5 on 2022-08-05 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0033_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registernewproject',
            name='projectid',
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 10, 35, 42, 321813), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 35, 42, 321813), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 10, 35, 42, 321813), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 35, 42, 321813), max_length=100),
        ),
    ]
