# Generated by Django 4.0.5 on 2022-08-05 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0035_remove_registernewproject_folderstructure_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 10, 40, 7, 761668), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='file',
            field=models.FileField(upload_to='Solar_Rooftop/Solar'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 40, 7, 761668), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 10, 40, 7, 761668), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 40, 7, 761668), max_length=100),
        ),
    ]
