# Generated by Django 4.0.5 on 2022-08-05 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0037_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarrooftop',
            name='File_Version1',
            field=models.FileField(null=True, upload_to='Solar_Rooftop/File_version1'),
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='File_Version2',
            field=models.FileField(null=True, upload_to='Solar_Rooftop/File_version2'),
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='File_Version3',
            field=models.FileField(null=True, upload_to='Solar_Rooftop/File_version3'),
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='File_Version4',
            field=models.FileField(null=True, upload_to='Solar_Rooftop/File_version4'),
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='File_Version5',
            field=models.FileField(null=True, upload_to='Solar_Rooftop/File_version5'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 14, 20, 28, 689681), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 14, 20, 28, 689681), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 14, 20, 28, 689681), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 14, 20, 28, 689681), max_length=100),
        ),
    ]
