# Generated by Django 4.0.5 on 2022-08-16 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0039_remove_solarrooftop_file_version1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version2',
            field=models.FileField(default='-', null=True, upload_to='Solar_Rooftop/File_version2'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version3',
            field=models.FileField(default='-', null=True, upload_to='Solar_Rooftop/File_version3'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version4',
            field=models.FileField(default='-', null=True, upload_to='Solar_Rooftop/File_version4'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version5',
            field=models.FileField(default='-', null=True, upload_to='Solar_Rooftop/File_version5'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 18, 55, 40, 434678), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 55, 40, 434678), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 18, 55, 40, 434678), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 55, 40, 434678), max_length=100),
        ),
    ]
