# Generated by Django 4.0.5 on 2022-08-22 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0041_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarrooftop',
            name='status2',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='status3',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='status4',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solarrooftop',
            name='status5',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 9, 57, 44, 814932), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 57, 44, 814932), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 9, 57, 44, 814932), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 57, 44, 814932), max_length=100),
        ),
    ]
