# Generated by Django 4.0.5 on 2022-08-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0043_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarrooftop',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='solarrooftop',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='solarrooftop',
            name='status4',
        ),
        migrations.RemoveField(
            model_name='solarrooftop',
            name='status5',
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 13, 7, 16, 738646), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 13, 7, 16, 738646), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 13, 7, 16, 738646), max_length=100),
        ),
        migrations.AlterField(
            model_name='tr401',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 13, 7, 16, 738646), max_length=100),
        ),
    ]
