# Generated by Django 4.0.5 on 2022-08-26 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0044_remove_solarrooftop_status2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TR401',
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 15, 32, 2, 564527), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 15, 32, 2, 564527), max_length=100),
        ),
    ]
