# Generated by Django 4.0.5 on 2022-08-27 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0046_project_eep5_alter_solarrooftop_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_eep5',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 15, 2, 26, 675136), max_length=100),
        ),
        migrations.AlterField(
            model_name='project_eep5',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 2, 26, 675136), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 15, 2, 26, 675136), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 2, 26, 675136), max_length=100),
        ),
    ]
