# Generated by Django 4.0.5 on 2022-09-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0049_projectee_delete_projecteep5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectee',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='solarrooftop',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 11, 11, 14, 128861), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 11, 11, 14, 128861), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 11, 11, 14, 128861), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 11, 11, 14, 128861), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
