# Generated by Django 4.0.5 on 2022-09-19 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0050_remove_projectee_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 21, 36, 123081), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='inputFile_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 10, 21, 36, 123081), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 10, 21, 36, 123081), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateTimeField(max_length=100),
        ),
    ]
