# Generated by Django 4.0.5 on 2022-09-19 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0053_alter_projectee_endfile_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registernewproject',
            name='room',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 11, 13, 29, 803675), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='inputFile_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 11, 13, 29, 803675), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 11, 13, 29, 803675), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 11, 13, 29, 803675), max_length=100),
        ),
    ]
