# Generated by Django 4.0.5 on 2022-09-19 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0054_registernewproject_room_alter_projectee_endfile_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registernewproject',
            old_name='room',
            new_name='specific_areas',
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 11, 17, 9, 380606), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='inputFile_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 11, 17, 9, 380606), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 11, 17, 9, 380606), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 11, 17, 9, 380606), max_length=100),
        ),
    ]
