# Generated by Django 4.0.5 on 2022-09-20 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0055_rename_room_registernewproject_specific_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOGGING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Who_Action', models.TextField()),
                ('Action', models.TextField()),
                ('Project', models.TextField()),
                ('Action_Time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 15, 23, 45, 99830), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='inputFile_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 20, 15, 23, 45, 99830), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 15, 23, 45, 99830), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='inputFile_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 20, 15, 23, 45, 99830), max_length=100),
        ),
    ]
