# Generated by Django 4.0.6 on 2022-09-28 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0077_alter_mlfaultdetection_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 8, 42, 2, 339042), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 8, 42, 2, 339042), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version2',
            field=models.FileField(default='-', null=True, upload_to='HAS_Cleanroom_10K/File_version2'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version3',
            field=models.FileField(default='-', null=True, upload_to='HAS_Cleanroom_10K/File_version3'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 8, 42, 2, 339042)),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='file',
            field=models.FileField(default='-', upload_to='HAS_Cleanroom_10K'),
        ),
    ]
