# Generated by Django 4.0.6 on 2022-10-27 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0078_alter_mlfaultdetection_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='File_Version2',
            field=models.FileField(default='-', null=True, upload_to='DIUDI Improvement/File_version2'),
        ),
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='File_Version3',
            field=models.FileField(default='-', null=True, upload_to='DIUDI Improvement/File_version3'),
        ),
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='File_Version4',
            field=models.FileField(default='-', null=True, upload_to='DIUDI Improvement/File_version4'),
        ),
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='File_Version5',
            field=models.FileField(default='-', null=True, upload_to='DIUDI Improvement/File_version5'),
        ),
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 13, 50, 34, 630167), max_length=100),
        ),
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='file',
            field=models.FileField(default='-', upload_to='DIUDI Improvement'),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='File_Version2',
            field=models.FileField(default='-', null=True, upload_to='As-build drawing P5 package/File_version2'),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='File_Version3',
            field=models.FileField(default='-', null=True, upload_to='As-build drawing P5 package/File_version3'),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='File_Version4',
            field=models.FileField(default='-', null=True, upload_to='As-build drawing P5 package/File_version4'),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='File_Version5',
            field=models.FileField(default='-', null=True, upload_to='As-build drawing P5 package/File_version5'),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 13, 50, 34, 630167), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='file',
            field=models.FileField(default='-', upload_to='PROJEAs-build drawing P5 packageCT_EEP5'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 20, 13, 50, 34, 630167)),
        ),
    ]
