# Generated by Django 4.0.6 on 2022-11-08 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0080_smartchecksheet_sub1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMARTCHECKSHEETSUBONE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=255, null=True)),
                ('inputFile_date', models.DateTimeField(auto_now_add=True)),
                ('endFile_date', models.DateField(default=datetime.datetime(2023, 11, 1, 14, 47, 50, 544577), max_length=100)),
                ('status', models.CharField(default='-', max_length=20, null=True)),
                ('file', models.FileField(default='-', upload_to='Smart Check Sheet for Substation1')),
                ('File_Version2', models.FileField(default='-', null=True, upload_to='Smart Check Sheet for Substation1/File_version2')),
                ('File_Version3', models.FileField(default='-', null=True, upload_to='Smart Check Sheet for Substation1/File_version3')),
                ('File_Version4', models.FileField(default='-', null=True, upload_to='Smart Check Sheet for Substation1/File_version4')),
                ('File_Version5', models.FileField(default='-', null=True, upload_to='Smart Check Sheet for Substation1/File_version5')),
            ],
        ),
        migrations.DeleteModel(
            name='SMARTCHECKSHEET_SUB1',
        ),
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 14, 47, 50, 544577), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 14, 47, 50, 543576), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 14, 47, 50, 543576)),
        ),
    ]
