# Generated by Django 4.0.5 on 2022-11-30 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0082_alter_mlfaultdetection_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 10, 5, 6, 314068), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 10, 5, 6, 314068), max_length=100),
        ),
        migrations.AlterField(
            model_name='smartchecksheetsubone',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 10, 5, 6, 314068), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 10, 5, 6, 309557)),
        ),
    ]
