# Generated by Django 4.0.5 on 2022-11-30 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0083_alter_mlfaultdetection_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 14, 26, 14, 58058), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 14, 26, 14, 53762), max_length=100),
        ),
        migrations.AlterField(
            model_name='smartchecksheetsubone',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 14, 26, 14, 59053), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version2',
            field=models.FileField(default='-', null=True, upload_to='SmartCheckSheet_Sub1/File_version2'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version3',
            field=models.FileField(default='-', null=True, upload_to='SmartCheckSheet_Sub1/File_version3'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version4',
            field=models.FileField(default='-', null=True, upload_to='SmartCheckSheet_Sub1/File_version4'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version5',
            field=models.FileField(default='-', null=True, upload_to='SmartCheckSheet_Sub1/File_version5'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 14, 26, 14, 38108)),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='file',
            field=models.FileField(default='-', upload_to='SmartCheckSheet_Sub1'),
        ),
    ]
