# Generated by Django 4.0.6 on 2022-12-12 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registernewproject', '0084_alter_mlfaultdetection_endfile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlfaultdetection',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 9, 44, 46, 475351), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectee',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 9, 44, 46, 475351), max_length=100),
        ),
        migrations.AlterField(
            model_name='smartchecksheetsubone',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 9, 44, 46, 475351), max_length=100),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version2',
            field=models.FileField(default='-', null=True, upload_to='CheckSheet_Sub1/File_version2'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version3',
            field=models.FileField(default='-', null=True, upload_to='CheckSheet_Sub1/File_version3'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version4',
            field=models.FileField(default='-', null=True, upload_to='CheckSheet_Sub1/File_version4'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='File_Version5',
            field=models.FileField(default='-', null=True, upload_to='CheckSheet_Sub1/File_version5'),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='endFile_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 9, 44, 46, 475351)),
        ),
        migrations.AlterField(
            model_name='solarrooftop',
            name='file',
            field=models.FileField(default='-', upload_to='CheckSheet_Sub1'),
        ),
    ]
